language: go
go:
  - 1.14.x

dist: xenial
services:
  - docker

env:
  global:
    - IP=127.0.0.1
    - USER_NAME=$(whoami)
    - KUBECONFIG_FOLDER_PATH=/home/$USER_NAME/.kube
    - KUBECONFIG_PATH=$KUBECONFIG_FOLDER_PATH/config
    - KUBECONFIG=$KUBECONFIG_PATH
    - KUBECTL_VERSION=v1.16.8

jobs:
  include:
    - stage: test
      name: faas-swarm
      env:
        - OPENFAAS_URL=http://$IP:8080/
      before_install:
        - docker swarm init
        - git clone https://github.com/openfaas/faas.git
        - cd faas && echo "$(pwd)" && ./deploy_stack.sh --no-auth && cd ..
        - sleep 10
      script: make test-swarm
      after_script:
        - "docker swarm leave --force"
    # stage key is omitted because it is still par of "test" and run in parallel
    - name: faas-netes
      env:
        - OPENFAAS_URL=http://$IP:31112/
      before_install:
        - curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl &&
          chmod +x kubectl && sudo mv kubectl /usr/local/bin/
        - sudo curl -sLS https://get.k3sup.dev | sh
        - sudo install k3sup /usr/local/bin/
        - mkdir -p $KUBECONFIG_FOLDER_PATH
        - k3sup install --local --ip $IP --user $USER_NAME
        - cp `pwd`/kubeconfig $KUBECONFIG_PATH
        - curl -sLS https://dl.get-arkade.dev | sudo sh
        - arkade install openfaas --basic-auth=false
        - kubectl rollout status -n openfaas deploy/gateway -w
      script: make test-kubernetes
